### ISSUE TITLE
Fail early if we're not uptodate with origin

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/polyglot-release#57] opened 2022-05-12 09:44 UTC
### 🤔 What's the problem you're trying to solve?

A clear error message if we haven't pulled the latest. I made a release while I had forgotten to pull first, and a tag was made which I had to go and clean up.

### ✨ What's your proposed solution?

Run this early on:

```bash
git fetch origin
status=$(git status)
echo "${status}" | grep "Your branch is behind"
if [ $? -e 0 ]; then
  echo "${status}" > /dev/stderr
  exit 1
fi
```

### ⛏ Have you considered any alternatives or workarounds?

No

**Comment by mpkorstanje** [comment] 2022-05-12 09:46
Duplicate of https://github.com/cucumber/polyglot-release/issues/43

**Closed by mpkorstanje** 2022-05-12 09:46 UTC
